name: HealthAPI
main: healthapi.HealthMainClass
version: "1.3.1-CHANGE"
api: ["1.0.9"]
load: POSTWORLD
author: SmallasWater

permissions:
  healthapi.vh:
    description: "设置虚拟血量"
    default: op